printWidth: 100
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: always
overrides:
  - files: '*.{yaml,yml,json,md}'
    options:
      tabWidth: 2
